import type { LucideIcon } from 'lucide-react'
import {
  Apple,
  Atom,
  Award,
  Baby,
  Balloon,
  BicepsFlexed,
  Binoculars,
  Bird,
  Book,
  BookMarked,
  BookOpen,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Camera,
  Candy,
  Cloud,
  Compass,
  Cookie,
  Dices,
  Drum,
  FaceSlightlySmiling,
  Feather,
  Fish,
  FlaskConical,
  Flower,
  Footprints,
  Gamepad2,
  Gift,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  House,
  IceCreamCone,
  Landmark,
  Languages,
  Leaf,
  LeafyGreen,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MicVocal,
  Microscope,
  Milestone,
  MoonStar,
  Mountain,
  Music,
  NotebookPen,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PencilSparkles,
  PenLine,
  PersonStanding,
  Pizza,
  Plane,
  Popcorn,
  Puzzle,
  Recycle,
  Ribbon,
  Rocket,
  Route,
  Sandwich,
  School,
  ScrollText,
  Shapes,
  Shirt,
  Soup,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Telescope,
  TentTree,
  Ticket,
  Timer,
  TrainFront,
  TreePalm,
  TreePine,
  Trees,
  Trophy,
  Users,
  UsersRound,
  Utensils,
  Video,
  Volleyball,
  WavesHorizontal,
} from 'lucide-react'

/**
 * The closed set of icons an editor can pick, and the only place a name resolves
 * to a component.
 *
 * **A key here is a stored database value.** Keys are lucide's own export names
 * so shorthand keeps name and component from drifting, and so no deprecated
 * alias (`Smile` for `FaceSlightlySmiling`) can be stored and break on a major.
 * Flat and domain-neutral: grouping by what a school uses an icon *for* would
 * put content vocabulary in the codebase — `scripts/icon-picker/` holds that
 * grouping and exports this list.
 *
 * Adding an icon needs no migration; removing one does — see
 * `docs/workflows/migrations.md`, and audit first with
 * `payload run scripts/audit-icon-usage.ts`.
 */
const REGISTRY = {
  Apple,
  Atom,
  Award,
  Baby,
  Balloon,
  BicepsFlexed,
  Binoculars,
  Bird,
  Book,
  BookMarked,
  BookOpen,
  Brush,
  Bug,
  Building2,
  Bus,
  Cake,
  CakeSlice,
  Calculator,
  Camera,
  Candy,
  Cloud,
  Compass,
  Cookie,
  Dices,
  Drum,
  FaceSlightlySmiling,
  Feather,
  Fish,
  FlaskConical,
  Flower,
  Footprints,
  Gamepad2,
  Gift,
  Globe,
  Goal,
  GraduationCap,
  Guitar,
  HandCoins,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  House,
  IceCreamCone,
  Landmark,
  Languages,
  Leaf,
  LeafyGreen,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MicVocal,
  Microscope,
  Milestone,
  MoonStar,
  Mountain,
  Music,
  NotebookPen,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pencil,
  PencilSparkles,
  PenLine,
  PersonStanding,
  Pizza,
  Plane,
  Popcorn,
  Puzzle,
  Recycle,
  Ribbon,
  Rocket,
  Route,
  Sandwich,
  School,
  ScrollText,
  Shapes,
  Shirt,
  Soup,
  Sparkles,
  Sprout,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Telescope,
  TentTree,
  Ticket,
  Timer,
  TrainFront,
  TreePalm,
  TreePine,
  Trees,
  Trophy,
  Users,
  UsersRound,
  Utensils,
  Video,
  Volleyball,
  WavesHorizontal,
} as const

export type IconName = keyof typeof REGISTRY

/**
 * Widened deliberately: as a union of each icon's distinct
 * `ForwardRefExoticComponent`, TypeScript refuses to call it in JSX.
 */
export const ICONS: Record<IconName, LucideIcon> = REGISTRY

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

export function isIconName(value: unknown): value is IconName {
  return typeof value === 'string' && value in ICONS
}

/**
 * Set `DoodleLayer` draws from when a caller passes no `icons`. Decorative
 * shapes only — a `Timer` drifting through a background reads as a UI control.
 */
export const AMBIENT_ICON_NAMES = [
  'Cloud',
  'FaceSlightlySmiling',
  'Feather',
  'Flower',
  'Music',
  'Palette',
  'PenLine',
  'Rocket',
  'Sparkles',
  'Star',
  'Sun',
] as const satisfies readonly IconName[]

/** Turns `GraduationCap` into `Graduation Cap`; derived so no label list can drift. */
export function iconLabel(name: IconName): string {
  return name
    .replace(/([a-z\d])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
}
