import next from 'eslint-config-next/core-web-vitals'
import prettier from 'eslint-config-prettier'
import unicorn from 'eslint-plugin-unicorn'
import tseslint from 'typescript-eslint'

/**
 * Lint rules fall into two groups:
 *
 *   1. Correctness — Next's recommended set plus typed TypeScript rules.
 *   2. Convention — the AGENTS.md rules that are mechanically checkable.
 *
 * Group 2 exists because conventions that live only in prose get violated by
 * every new contributor, and catching them in review costs a round trip every
 * time. If a rule below feels wrong, change it here deliberately rather than
 * adding inline disables.
 */
/** Colours, spacing, and radii come from tokens. See docs/design/tokens.md. */
const NO_RAW_COLOURS = [
  {
    selector: 'Literal[value=/#(?:[0-9a-fA-F]{3,4}){1,2}\\b/]',
    message: 'No raw hex colours. Use a design token — see docs/design/tokens.md.',
  },
  {
    selector: 'Literal[value=/\\b(?:rgb|hsl)a?\\(/]',
    message: 'No raw colour functions. Use a design token — see docs/design/tokens.md.',
  },
]

/**
 * Catches `process.env.FOO` and `process.env[key]` alike — the selector matches
 * the `process.env` member expression itself, so the access style after it does
 * not matter.
 */
const NO_PROCESS_ENV = {
  selector: "MemberExpression[object.name='process'][property.name='env']",
  message: 'Read environment variables through src/lib/env.ts, not process.env directly.',
}

export default tseslint.config(
  {
    ignores: [
      '.claude/**',
      '.next/**',
      'node_modules/**',
      '_reference/**',
      // Generated by scripts/copy-maplibre-worker.mjs — third-party build output.
      'public/maplibre/**',
      'next-env.d.ts',
      'src/app/(payload)/admin/importMap.js',
      'src/payload-types.ts',
      'src/payload/migrations/**',
    ],
  },

  ...next,
  ...tseslint.configs.recommended,

  {
    plugins: { unicorn },
    rules: {
      // kebab-case filenames. Route-group and dynamic-segment directories are
      // Next's own syntax, so bracketed and parenthesised names are allowed.
      'unicorn/filename-case': [
        'error',
        {
          case: 'kebabCase',
          ignore: [/^\[.*\]/, /^\(.*\)/, /^README\.md$/, /^AGENTS\.md$/, /^DESIGN\.md$/],
        },
      ],

      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
    },
  },

  // Convention rules. Flat config replaces a rule wholesale rather than
  // merging it, so every selector for `no-restricted-syntax` that should apply
  // to a given file has to be listed together in the block that wins.
  {
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/env.ts', 'src/lib/brand-colours.ts'],
    rules: {
      'no-restricted-syntax': ['error', ...NO_RAW_COLOURS, NO_PROCESS_ENV],
    },
  },

  // Payload collection, global, and block configs are data, not application
  // logic — they legitimately hold long literal strings. The environment rule
  // still applies: config files have no business reading env vars directly.
  {
    files: [
      'src/payload/collections/**',
      'src/payload/globals/**',
      'src/payload/blocks/**/config.ts',
    ],
    rules: {
      'no-restricted-syntax': ['error', NO_PROCESS_ENV],
    },
  },

  // Must stay last: turns off everything that fights Prettier.
  prettier,
)
