// The curated icon set, grouped only to make review easier.
// Groups are NOT shipped — the real registry (src/lib/icons.ts) is flat.
// Canonical lucide export names only, never deprecated aliases: aliases get
// removed in majors, and these strings are persisted in the database.
//
// To add an icon: run the picker (see README.md), search the full lucide set,
// mark it, export, and paste the result back here.

export const GROUPS = [
  {
    id: 'core',
    label: 'Core / decorative',
    icons: [
      'Star',
      'Sun',
      'Sunrise',
      'Sunset',
      'Cloud',
      'Sparkles',
      'FaceSlightlySmiling',
      'Feather',
      'Flower',
      'Music',
      'Palette',
      'PenLine',
      'Rocket',
    ],
  },
  {
    id: 'education',
    label: 'Education',
    icons: [
      'GraduationCap',
      'School',
      'Book',
      'BookOpen',
      'BookMarked',
      'ScrollText',
      'NotebookPen',
      'Pencil',
      'Brush',
      'Paintbrush',
      'Calculator',
      'Microscope',
      'FlaskConical',
      'Atom',
      'Telescope',
      'Globe',
      'Languages',
      'Lightbulb',
      'Shapes',
      'Puzzle',
      'Apple',
      'Baby',
    ],
  },
  {
    id: 'sports',
    label: 'Sports day / fun run',
    icons: [
      'Trophy',
      'Medal',
      'Award',
      'Ribbon',
      'Goal',
      'Timer',
      'Volleyball',
      'BicepsFlexed',
      'PersonStanding',
      'Footprints',
      'Route',
      'Milestone',
      'Shirt',
      'WavesHorizontal',
    ],
  },
  {
    id: 'trips',
    label: 'Field trips',
    icons: [
      'Bus',
      'TrainFront',
      'Plane',
      'Map',
      'MapPin',
      'Compass',
      'Binoculars',
      'TentTree',
      'TreePine',
      'TreePalm',
      'Trees',
      'Mountain',
      'Leaf',
      'LeafyGreen',
      'Bird',
      'Bug',
      'Fish',
      'PawPrint',
      'Recycle',
      'Camera',
      'Ticket',
      'Landmark',
      'Building2',
      'Luggage',
      'Sandwich',
    ],
  },
  {
    id: 'community',
    label: 'Community service',
    icons: [
      'HeartHandshake',
      'Handshake',
      'HandHeart',
      'HandCoins',
      'Heart',
      'Users',
      'UsersRound',
      'Gift',
      'Sprout',
      'Soup',
      'Utensils',
      'House',
      'Megaphone',
    ],
  },
  {
    id: 'celebration',
    label: 'Celebration / fun',
    icons: [
      'PartyPopper',
      'Balloon',
      'Cake',
      'CakeSlice',
      'Cookie',
      'Candy',
      'Pizza',
      'Popcorn',
      'IceCreamCone',
      'Drum',
      'Guitar',
      'MicVocal',
      'Video',
      'Dices',
      'Gamepad2',
      'PencilSparkles',
      'MoonStar',
    ],
  },
]

// Seeded-random decorative set used by DoodleLayer.
// Subset of the registry — marking ambient implies picker.
export const AMBIENT_DEFAULT = [
  'Cloud',
  'FaceSlightlySmiling',
  'Feather',
  'Flower',
  'Music',
  'Palette',
  'PenLine',
  'Rocket',
  'Sparkles',
  'Star',
  'Sun',
]

// Old kebab-case select values, before the switch to export names as stored values.
// Anything here that is NOT in RENAME_MAP is purged by the migration.
export const LEGACY_VALUES = [
  'star',
  'sun',
  'sunrise',
  'sunset',
  'cloud',
  'sparkles',
  'smile',
  'feather',
  'flower',
  'music',
  'palette',
  'pen-line',
  'rocket',
  'zap',
  'rainbow',
]

export const RENAME_MAP = {
  star: 'Star',
  sun: 'Sun',
  sunrise: 'Sunrise',
  sunset: 'Sunset',
  cloud: 'Cloud',
  sparkles: 'Sparkles',
  smile: 'FaceSlightlySmiling',
  feather: 'Feather',
  flower: 'Flower',
  music: 'Music',
  palette: 'Palette',
  'pen-line': 'PenLine',
  rocket: 'Rocket',
}

// Legacy values with no replacement — migration nulls these, audit script reports them first.
export const PENDING_PURGE = ['zap', 'rainbow']
